# Slim version of Python
FROM python:3.8.12-slim

# Download Package Information
RUN apt-get update -y

# Install Tkinter
RUN apt-get install tk -y

RUN pip3 install myqlm qiskit turtle myqlm-interop

# Commands to run application
CMD ["qiskit-myqlm-1.py"]
ENTRYPOINT ["python3"]