# Slim version of Python
FROM python:3.8.12-slim

# Download Package Information
RUN apt-get update -y

# Install Tkinter
RUN apt-get install tk -y
RUN python3 -m pip install --upgrade pip
RUN pip3 install cython cmake scikit-build
RUN pip3 install myqlm qiskit myqlm-interop

COPY qiskit-myqlm-1.py /tmp/qiskit-myqlm-1.py
# Commands to run application
CMD ["/mtp/qiskit-myqlm-1.py"]
ENTRYPOINT ["python3"]